Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
//Leia um valor inteiro X. Em seguida mostre os ímpares de 1 até X,
//um valor por linha, inclusive o X, se for o caso
Var
  x, i: inteiro

Inicio

   escreva("Digite o valor de X:")
   leia(x)

   para i de 1 ate x faca
      se i % 2 <> 0 entao
         escreval(i)
      fimse
   fimpara



Fimalgoritmo